site_name: "pyapp-kit"
site_url: https://pyapp-kit.github.io/
site_description: "A collection of tools for making Python applications."
repo_url: https://github.com/pyapp-kit/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - toc:
      permalink: "#"

plugins:
  - search
  - spellcheck:
      backends:
        - codespell:
            dictionaries: [clear]
