name: deploy docs
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - uses: astral-sh/setup-uv@v6
      - if: ${{ github.event_name == 'pull_request' }}
        run: uv run mkdocs build --strict
      - if: ${{ github.event_name == 'push' }}
        run: uv run mkdocs gh-deploy --strict --force
